# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afcba97905e66edccb07a0a605c5a9e345d2d2edf7c07a713cf44aa913ead5bf5bfa46dfe4972d350636778d7d43518786152e0e93312ed64ff1b773b53f4638

test:
  secret_key_base: 41c2ad033a171fdf01fb3f40c901be0289c4bb1ee901600122ef1b62c8a31a6df2ae4c3120e45c07c80776e8d7c51b0b1705118a3baa4af7ff8f45f2bfd0e4ba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
